#Site settings
tite: Artists Theme
email: artist@gmail.com
description: "Thinker // Designer // YouTuber"

# Build settings
markdown: kramdown
permalink: pretty
port: 3000
sass:
sass_dir: assets/css
style: :nested