#Basic content settings
title: Artists Theme
email: artist@gmail.com
description: "Thinker // Designer // YouTuber"


#animations:
bg-img: "hero-bg.jpg"
logo: "logo.svg"
avatar: "travitar.jpg"
blurb: <p><strong>Travis specializes in making things for human people. </strong> Most of the things he makes are digital interfaces but he also puts effort into crafting next-level beats and YouTube videos about making codes happen.</p>

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}

projects:
- {name: Typo International Design Talks, folder: 'proj-1'}
- {name: City-IN website concept, folder: 'proj-2'}
- {name: Crisp Icons, folder: 'proj-3'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4'}
- {name: Fresh It Up, folder: 'proj-5'}
- {name: Timeline Page, folder: 'proj-6'}
- {name: Weather Dashboard, folder: 'proj-7'}
- {name: Stripes & Co, folder: 'proj-8'}

clients:
- {avatar: 'face-aaroni.jpg', name: 'Scott Summers', title: 'Director of Design Quebec Int.', quote: '<p><strong>Lorem ipsum dolor sit amet</strong>, etiam vitae elit leo in torquent, nullam in libero mattis, aut aenean adipiscing lacus donec dis, nec pharetra viverra nulla sed donec porta, magna condimentum mollis nulla wisi. Lacinia imperdiet justo magna repudiandae, duis metus ut nibh tortor dictum metus. Magna eget a et. Amet duis elit diam, augue nec semper. Eros proin vitae, tellus amet.</p>', logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg', name: 'Scott Summers', title: 'Director of Design Quebec Int.', quote: '<p><strong>Lorem ipsum dolor sit amet</strong>, etiam vitae elit leo in torquent, nullam in libero mattis, aut aenean adipiscing lacus donec dis, nec pharetra viverra nulla sed donec porta, magna condimentum mollis nulla wisi. Lacinia imperdiet justo magna repudiandae, duis metus ut nibh tortor dictum metus. Magna eget a et. Amet duis elit diam, augue nec semper. Eros proin vitae, tellus amet.</p>', logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg', name: 'Scott Summers', title: 'Director of Design Quebec Int.', quote: '<p><strong>Lorem ipsum dolor sit amet</strong>, etiam vitae elit leo in torquent, nullam in libero mattis, aut aenean adipiscing lacus donec dis, nec pharetra viverra nulla sed donec porta, magna condimentum mollis nulla wisi. Lacinia imperdiet justo magna repudiandae, duis metus ut nibh tortor dictum metus. Magna eget a et. Amet duis elit diam, augue nec semper. Eros proin vitae, tellus amet.</p>', logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg', name: 'Scott Summers', title: 'Director of Design Quebec Int.', quote: '<p><strong>Lorem ipsum dolor sit amet</strong>, etiam vitae elit leo in torquent, nullam in libero mattis, aut aenean adipiscing lacus donec dis, nec pharetra viverra nulla sed donec porta, magna condimentum mollis nulla wisi. Lacinia imperdiet justo magna repudiandae, duis metus ut nibh tortor dictum metus. Magna eget a et. Amet duis elit diam, augue nec semper. Eros proin vitae, tellus amet.</p>', logo: 'logo4.png'}

social:
- {icon: 'twitter', link: 'http://twitter,com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behancenet/travisneilson'}
- {icon: 'youtube', link: 'https://youtube.com'}
- {icon: 'linkedin', link: 'https://linkedin.com'}